### ISSUE TITLE
Allow JSON comments in slug.json

### ISSUE THREAD

**Issue by AndiDog** [spine/hem#91]
As the title says, it would be nice to be able to document the slug.json file directly with // and /\* */ comments. Right now this throws an error because JSON.parse is used directly (see readSlug method), which doesn't allow the non-standard comments.

For example this way?: http://stackoverflow.com/a/11784664/245706

**Comment by aeischeid** [comment]
having moved to use slug.coffee we have this. shall we close this then @cengebretson ?

**Comment by AndiDog** [comment]
I didn't even remember I opened this ;) Let's close... Much nicer to configure with CoffeeScript.
